spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
        
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Ragil404*
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect



spring:
  profiles:
    active: dev

